### Create record
POST http://localhost:8090/api/v1/record
Content-Type: application/json
Accept: application/json

{
  "recordId": "1",
  "time": "2025-12-18T13:00:00Z",
  "sourceId": "SRC-001",
  "destinationId": "DST-001",
  "type": "positive",
  "value": 123,
  "unit": "kg",
  "reference": "shipment-2025-001"
}

> {%
    client.assert(response.status === 200, "Status should be 200")
%}
